# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_preprocessing.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_data_preprocessing(object):
    def setupUi(self, data_preprocessing):
        data_preprocessing.setObjectName("data_preprocessing")
        data_preprocessing.resize(518, 754)
        data_preprocessing.setStyleSheet("background: None;")
        self.verticalLayout = QtWidgets.QVBoxLayout(data_preprocessing)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(data_preprocessing)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setVerticalSpacing(9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.drop_feature_by_index = QtWidgets.QCheckBox(self.groupBox_3)
        self.drop_feature_by_index.setChecked(True)
        self.drop_feature_by_index.setObjectName("drop_feature_by_index")
        self.gridLayout_3.addWidget(self.drop_feature_by_index, 1, 0, 1, 1)
        self.drop_index = QtWidgets.QLineEdit(self.groupBox_3)
        self.drop_index.setObjectName("drop_index")
        self.gridLayout_3.addWidget(self.drop_index, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 2, 1, 1)
        self.onehot_index = QtWidgets.QLineEdit(self.groupBox_3)
        self.onehot_index.setObjectName("onehot_index")
        self.gridLayout_3.addWidget(self.onehot_index, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 3, 1, 1)
        self.trans_into_ordinal = QtWidgets.QCheckBox(self.groupBox_3)
        self.trans_into_ordinal.setObjectName("trans_into_ordinal")
        self.gridLayout_3.addWidget(self.trans_into_ordinal, 2, 0, 1, 1)
        self.ordinal_index = QtWidgets.QLineEdit(self.groupBox_3)
        self.ordinal_index.setObjectName("ordinal_index")
        self.gridLayout_3.addWidget(self.ordinal_index, 2, 2, 1, 1)
        self.trans_into_onehot = QtWidgets.QCheckBox(self.groupBox_3)
        self.trans_into_onehot.setObjectName("trans_into_onehot")
        self.gridLayout_3.addWidget(self.trans_into_onehot, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.groupBox = QtWidgets.QGroupBox(data_preprocessing)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 100))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.drop_feature_by_threshold = QtWidgets.QCheckBox(self.groupBox)
        self.drop_feature_by_threshold.setChecked(True)
        self.drop_feature_by_threshold.setObjectName("drop_feature_by_threshold")
        self.gridLayout_2.addWidget(self.drop_feature_by_threshold, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.threshold_sb = QtWidgets.QSpinBox(self.groupBox)
        self.threshold_sb.setProperty("value", 90)
        self.threshold_sb.setObjectName("threshold_sb")
        self.gridLayout_2.addWidget(self.threshold_sb, 0, 2, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 2, 2, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.groupBox_4 = QtWidgets.QGroupBox(data_preprocessing)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_4.setObjectName("groupBox_4")
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setGeometry(QtCore.QRect(30, 20, 262, 22))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_4.addWidget(self.checkBox_4, 0, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_4.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.groupBox_2 = QtWidgets.QGroupBox(data_preprocessing)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 250))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.buttonBox = QtWidgets.QDialogButtonBox(data_preprocessing)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(data_preprocessing)
        QtCore.QMetaObject.connectSlotsByName(data_preprocessing)

    def retranslateUi(self, data_preprocessing):
        _translate = QtCore.QCoreApplication.translate
        data_preprocessing.setWindowTitle(_translate("data_preprocessing", "Data Preprocessing"))
        self.groupBox_3.setTitle(_translate("data_preprocessing", "Text Feature"))
        self.drop_feature_by_index.setText(_translate("data_preprocessing", "drop feature at column index of "))
        self.drop_index.setText(_translate("data_preprocessing", "0,482"))
        self.label_5.setText(_translate("data_preprocessing", "Feature index from 0"))
        self.trans_into_ordinal.setText(_translate("data_preprocessing", "transform the text feature into ordinal"))
        self.trans_into_onehot.setText(_translate("data_preprocessing", "transform the text feature into one-hot"))
        self.groupBox.setTitle(_translate("data_preprocessing", "Empty Cells"))
        self.label_4.setText(_translate("data_preprocessing", "or"))
        self.drop_feature_by_threshold.setText(_translate("data_preprocessing", "drop features have empty values more than"))
        self.label_2.setText(_translate("data_preprocessing", "%"))
        self.label_3.setText(_translate("data_preprocessing", "then"))
        self.checkBox_2.setText(_translate("data_preprocessing", "fill the empty cell with"))
        self.comboBox.setItemText(0, _translate("data_preprocessing", "median"))
        self.comboBox.setItemText(1, _translate("data_preprocessing", "mean"))
        self.comboBox.setItemText(2, _translate("data_preprocessing", "most_frequent"))
        self.checkBox_3.setText(_translate("data_preprocessing", "drop cases have empty value"))
        self.groupBox_4.setToolTip(_translate("data_preprocessing", "<html><head/><body><p>the class variable you want to predict</p></body></html>"))
        self.groupBox_4.setTitle(_translate("data_preprocessing", "Target Label"))
        self.checkBox_4.setText(_translate("data_preprocessing", "class variable at index of "))
        self.groupBox_2.setTitle(_translate("data_preprocessing", "Preview"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    data_preprocessing = QtWidgets.QDialog()
    ui = Ui_data_preprocessing()
    ui.setupUi(data_preprocessing)
    data_preprocessing.show()
    sys.exit(app.exec_())
