# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deal_with_empty_value.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Deal_With_Empty_Dialog(object):
    def setupUi(self, Deal_With_Empty_Dialog):
        Deal_With_Empty_Dialog.setObjectName("Deal_With_Empty_Dialog")
        Deal_With_Empty_Dialog.resize(518, 661)
        Deal_With_Empty_Dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Deal_With_Empty_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(Deal_With_Empty_Dialog)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setStyleSheet("font-weight:400;\n"
"font-size:16px;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.empty_cell_num_label = QtWidgets.QLabel(self.widget_2)
        self.empty_cell_num_label.setStyleSheet("font-weight:400;\n"
"font-size:16px;")
        self.empty_cell_num_label.setObjectName("empty_cell_num_label")
        self.horizontalLayout.addWidget(self.empty_cell_num_label)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setStyleSheet("font-weight:400;\n"
"font-size:16px;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.empty_cell_groupBox = QtWidgets.QGroupBox(Deal_With_Empty_Dialog)
        self.empty_cell_groupBox.setMinimumSize(QtCore.QSize(400, 170))
        self.empty_cell_groupBox.setObjectName("empty_cell_groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.empty_cell_groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.empty_cell_groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 1)
        self.drop_empty_case_cb = QtWidgets.QCheckBox(self.empty_cell_groupBox)
        self.drop_empty_case_cb.setObjectName("drop_empty_case_cb")
        self.gridLayout_2.addWidget(self.drop_empty_case_cb, 5, 0, 1, 1)
        self.drop_feature_by_threshold_cb = QtWidgets.QCheckBox(self.empty_cell_groupBox)
        self.drop_feature_by_threshold_cb.setChecked(True)
        self.drop_feature_by_threshold_cb.setObjectName("drop_feature_by_threshold_cb")
        self.gridLayout_2.addWidget(self.drop_feature_by_threshold_cb, 0, 0, 1, 1)
        self.fill_num_empty_with_cb = QtWidgets.QCheckBox(self.empty_cell_groupBox)
        self.fill_num_empty_with_cb.setChecked(True)
        self.fill_num_empty_with_cb.setObjectName("fill_num_empty_with_cb")
        self.gridLayout_2.addWidget(self.fill_num_empty_with_cb, 2, 0, 1, 1)
        self.threshold_sb = QtWidgets.QSpinBox(self.empty_cell_groupBox)
        self.threshold_sb.setProperty("value", 10)
        self.threshold_sb.setObjectName("threshold_sb")
        self.gridLayout_2.addWidget(self.threshold_sb, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.empty_cell_groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.fill_num_with_comb = QtWidgets.QComboBox(self.empty_cell_groupBox)
        self.fill_num_with_comb.setObjectName("fill_num_with_comb")
        self.fill_num_with_comb.addItem("")
        self.fill_num_with_comb.addItem("")
        self.fill_num_with_comb.addItem("")
        self.gridLayout_2.addWidget(self.fill_num_with_comb, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.empty_cell_groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.fill_text_with_cb = QtWidgets.QCheckBox(self.empty_cell_groupBox)
        self.fill_text_with_cb.setChecked(True)
        self.fill_text_with_cb.setObjectName("fill_text_with_cb")
        self.gridLayout_2.addWidget(self.fill_text_with_cb, 3, 0, 1, 1)
        self.fill_text_with_comb = QtWidgets.QComboBox(self.empty_cell_groupBox)
        self.fill_text_with_comb.setEditable(True)
        self.fill_text_with_comb.setObjectName("fill_text_with_comb")
        self.fill_text_with_comb.addItem("")
        self.gridLayout_2.addWidget(self.fill_text_with_comb, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.empty_cell_groupBox)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.table_groupBox = QtWidgets.QGroupBox(Deal_With_Empty_Dialog)
        self.table_groupBox.setMinimumSize(QtCore.QSize(500, 250))
        self.table_groupBox.setObjectName("table_groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.table_groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.table_groupBox)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.table_groupBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.widget = QtWidgets.QWidget(Deal_With_Empty_Dialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.finish_btn = QtWidgets.QPushButton(self.widget)
        self.finish_btn.setObjectName("finish_btn")
        self.gridLayout.addWidget(self.finish_btn, 0, 2, 1, 1)
        self.apply_btn = QtWidgets.QPushButton(self.widget)
        self.apply_btn.setObjectName("apply_btn")
        self.gridLayout.addWidget(self.apply_btn, 0, 0, 1, 1)
        self.reset_btn = QtWidgets.QPushButton(self.widget)
        self.reset_btn.setObjectName("reset_btn")
        self.gridLayout.addWidget(self.reset_btn, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(4, 3)
        self.verticalLayout.setStretch(6, 1)

        self.retranslateUi(Deal_With_Empty_Dialog)
        self.apply_btn.clicked.connect(Deal_With_Empty_Dialog.apply_handler)
        self.finish_btn.clicked.connect(Deal_With_Empty_Dialog.finish_handler)
        QtCore.QMetaObject.connectSlotsByName(Deal_With_Empty_Dialog)

    def retranslateUi(self, Deal_With_Empty_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Deal_With_Empty_Dialog.setWindowTitle(_translate("Deal_With_Empty_Dialog", "Deal With Empty values"))
        self.label.setText(_translate("Deal_With_Empty_Dialog", "The Data Have "))
        self.empty_cell_num_label.setText(_translate("Deal_With_Empty_Dialog", "0"))
        self.label_6.setText(_translate("Deal_With_Empty_Dialog", " Empty Cell(s)"))
        self.empty_cell_groupBox.setTitle(_translate("Deal_With_Empty_Dialog", "Empty Cells"))
        self.label_4.setText(_translate("Deal_With_Empty_Dialog", "or"))
        self.drop_empty_case_cb.setText(_translate("Deal_With_Empty_Dialog", "drop cases have empty value"))
        self.drop_feature_by_threshold_cb.setText(_translate("Deal_With_Empty_Dialog", "drop features have empty values more than"))
        self.fill_num_empty_with_cb.setText(_translate("Deal_With_Empty_Dialog", "fill numeric features\' empty cell with"))
        self.label_2.setText(_translate("Deal_With_Empty_Dialog", "%"))
        self.fill_num_with_comb.setItemText(0, _translate("Deal_With_Empty_Dialog", "median"))
        self.fill_num_with_comb.setItemText(1, _translate("Deal_With_Empty_Dialog", "mean"))
        self.fill_num_with_comb.setItemText(2, _translate("Deal_With_Empty_Dialog", "most_frequent"))
        self.label_3.setText(_translate("Deal_With_Empty_Dialog", "then"))
        self.fill_text_with_cb.setText(_translate("Deal_With_Empty_Dialog", "fill text features\' empty cell with"))
        self.fill_text_with_comb.setToolTip(_translate("Deal_With_Empty_Dialog", "只能选择众数或者输入一个自定义的类别（不推荐）"))
        self.fill_text_with_comb.setItemText(0, _translate("Deal_With_Empty_Dialog", "most_frequent"))
        self.table_groupBox.setTitle(_translate("Deal_With_Empty_Dialog", "Preview *unprocessed"))
        self.finish_btn.setText(_translate("Deal_With_Empty_Dialog", "Finish"))
        self.apply_btn.setText(_translate("Deal_With_Empty_Dialog", "Apply"))
        self.reset_btn.setText(_translate("Deal_With_Empty_Dialog", "Reset Data From Previous"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Deal_With_Empty_Dialog = QtWidgets.QDialog()
    ui = Ui_Deal_With_Empty_Dialog()
    ui.setupUi(Deal_With_Empty_Dialog)
    Deal_With_Empty_Dialog.show()
    sys.exit(app.exec_())
