# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_reader_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_file_reader_dialog(object):
    def setupUi(self, file_reader_dialog):
        file_reader_dialog.setObjectName("file_reader_dialog")
        file_reader_dialog.resize(518, 979)
        file_reader_dialog.setStyleSheet("background: None;")
        self.verticalLayout = QtWidgets.QVBoxLayout(file_reader_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(file_reader_dialog)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 100))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.open_train_file_btn = Open_File_Btn(self.groupBox)
        self.open_train_file_btn.setObjectName("open_train_file_btn")
        self.gridLayout.addWidget(self.open_train_file_btn, 0, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.display_train_file_name_label = QtWidgets.QLabel(self.groupBox)
        self.display_train_file_name_label.setStyleSheet("")
        self.display_train_file_name_label.setObjectName("display_train_file_name_label")
        self.gridLayout.addWidget(self.display_train_file_name_label, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.train_column_header_cb = QtWidgets.QCheckBox(self.groupBox)
        self.train_column_header_cb.setChecked(True)
        self.train_column_header_cb.setObjectName("train_column_header_cb")
        self.gridLayout.addWidget(self.train_column_header_cb, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.train_row_header_cb = QtWidgets.QCheckBox(self.groupBox)
        self.train_row_header_cb.setObjectName("train_row_header_cb")
        self.gridLayout.addWidget(self.train_row_header_cb, 2, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignVCenter)
        self.target_label_groupBox = QtWidgets.QGroupBox(file_reader_dialog)
        self.target_label_groupBox.setMinimumSize(QtCore.QSize(0, 50))
        self.target_label_groupBox.setObjectName("target_label_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.target_label_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 1, 1, 1)
        self.set_target_cb = QtWidgets.QCheckBox(self.target_label_groupBox)
        self.set_target_cb.setEnabled(False)
        self.set_target_cb.setChecked(True)
        self.set_target_cb.setObjectName("set_target_cb")
        self.gridLayout_4.addWidget(self.set_target_cb, 0, 0, 1, 1)
        self.target_index_comb = QtWidgets.QComboBox(self.target_label_groupBox)
        self.target_index_comb.setObjectName("target_index_comb")
        self.gridLayout_4.addWidget(self.target_index_comb, 0, 2, 1, 1)
        self.gridLayout_4.setColumnMinimumWidth(0, 1)
        self.gridLayout_4.setColumnMinimumWidth(2, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(2, 1)
        self.verticalLayout.addWidget(self.target_label_groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(file_reader_dialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 4)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 75))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.display_test_file_name_label = QtWidgets.QLabel(self.groupBox_4)
        self.display_test_file_name_label.setStyleSheet("")
        self.display_test_file_name_label.setObjectName("display_test_file_name_label")
        self.gridLayout_2.addWidget(self.display_test_file_name_label, 1, 1, 1, 1)
        self.load_test_from_cb = QtWidgets.QCheckBox(self.groupBox_4)
        self.load_test_from_cb.setEnabled(False)
        self.load_test_from_cb.setObjectName("load_test_from_cb")
        self.gridLayout_2.addWidget(self.load_test_from_cb, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.open_test_file_btn = Open_File_Btn(self.groupBox_4)
        self.open_test_file_btn.setEnabled(False)
        self.open_test_file_btn.setObjectName("open_test_file_btn")
        self.gridLayout_2.addWidget(self.open_test_file_btn, 0, 1, 1, 1)
        self.test_column_header_cb = QtWidgets.QCheckBox(self.groupBox_4)
        self.test_column_header_cb.setChecked(True)
        self.test_column_header_cb.setObjectName("test_column_header_cb")
        self.gridLayout_2.addWidget(self.test_column_header_cb, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.test_row_header_cb = QtWidgets.QCheckBox(self.groupBox_4)
        self.test_row_header_cb.setObjectName("test_row_header_cb")
        self.gridLayout_2.addWidget(self.test_row_header_cb, 2, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.split_method_comb = Split_Method_Combo(self.groupBox_5)
        self.split_method_comb.setObjectName("split_method_comb")
        self.split_method_comb.addItem("")
        self.split_method_comb.addItem("")
        self.gridLayout_3.addWidget(self.split_method_comb, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.test_radio = QtWidgets.QSpinBox(self.groupBox_5)
        self.test_radio.setSingleStep(5)
        self.test_radio.setProperty("value", 30)
        self.test_radio.setObjectName("test_radio")
        self.gridLayout_3.addWidget(self.test_radio, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 5, 1, 1)
        self.split_test_fro_train_cb = QtWidgets.QCheckBox(self.groupBox_5)
        self.split_test_fro_train_cb.setEnabled(False)
        self.split_test_fro_train_cb.setChecked(True)
        self.split_test_fro_train_cb.setObjectName("split_test_fro_train_cb")
        self.gridLayout_3.addWidget(self.split_test_fro_train_cb, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 3, 1, 1)
        self.gridLayout_3.setColumnMinimumWidth(0, 1)
        self.gridLayout_3.setColumnMinimumWidth(2, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.gridLayout_3.setColumnStretch(2, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.without_test_cb = QtWidgets.QCheckBox(self.groupBox_6)
        self.without_test_cb.setEnabled(False)
        self.without_test_cb.setChecked(False)
        self.without_test_cb.setObjectName("without_test_cb")
        self.verticalLayout_5.addWidget(self.without_test_cb)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(file_reader_dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(500, 300))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(400, 260))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.tableWidget_describe = Auxiliary_Table(self.groupBox_2)
        self.tableWidget_describe.setMinimumSize(QtCore.QSize(0, 100))
        self.tableWidget_describe.setObjectName("tableWidget_describe")
        self.tableWidget_describe.setColumnCount(0)
        self.tableWidget_describe.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget_describe)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.apply_btn = QtWidgets.QPushButton(file_reader_dialog)
        self.apply_btn.setEnabled(False)
        self.apply_btn.setObjectName("apply_btn")
        self.horizontalLayout_2.addWidget(self.apply_btn)
        self.finish_btn = QtWidgets.QPushButton(file_reader_dialog)
        self.finish_btn.setObjectName("finish_btn")
        self.horizontalLayout_2.addWidget(self.finish_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(file_reader_dialog)
        self.tableWidget.cellClicked['int','int'].connect(self.tableWidget_describe.select_column)
        self.tableWidget.cellChanged['int','int'].connect(self.tableWidget_describe.select_column)
        self.open_train_file_btn.file_path_changed.connect(file_reader_dialog.open_train_file_btn_clicked_handler)
        self.target_index_comb.currentIndexChanged['int'].connect(file_reader_dialog.target_label_changed_handler)
        self.set_target_cb.clicked['bool'].connect(self.split_method_comb.target_handler)
        self.apply_btn.clicked.connect(file_reader_dialog.apply_handler)
        self.finish_btn.clicked.connect(file_reader_dialog.finish_handler)
        self.open_test_file_btn.file_path_changed.connect(file_reader_dialog.open_test_file_btn_clicked_handler)
        self.set_target_cb.clicked.connect(file_reader_dialog.display_table)
        QtCore.QMetaObject.connectSlotsByName(file_reader_dialog)

    def retranslateUi(self, file_reader_dialog):
        _translate = QtCore.QCoreApplication.translate
        file_reader_dialog.setWindowTitle(_translate("file_reader_dialog", "File Reader Dialog"))
        self.groupBox.setTitle(_translate("file_reader_dialog", "Training Files"))
        self.open_train_file_btn.setText(_translate("file_reader_dialog", "Open Training File"))
        self.label.setText(_translate("file_reader_dialog", "Traing File Name: "))
        self.display_train_file_name_label.setText(_translate("file_reader_dialog", "No File Selected"))
        self.train_column_header_cb.setText(_translate("file_reader_dialog", "with column header at first row"))
        self.train_row_header_cb.setText(_translate("file_reader_dialog", "with row label at first column"))
        self.target_label_groupBox.setToolTip(_translate("file_reader_dialog", "<html><head/><body><p>the class variable you want to predict</p></body></html>"))
        self.target_label_groupBox.setTitle(_translate("file_reader_dialog", "Target Label"))
        self.set_target_cb.setText(_translate("file_reader_dialog", "response variable at index of "))
        self.groupBox_3.setTitle(_translate("file_reader_dialog", "Test Data Option"))
        self.groupBox_4.setTitle(_translate("file_reader_dialog", "independent testing file"))
        self.display_test_file_name_label.setText(_translate("file_reader_dialog", "No File Selcted"))
        self.load_test_from_cb.setText(_translate("file_reader_dialog", "load testing file from"))
        self.label_2.setText(_translate("file_reader_dialog", "Test File Name: "))
        self.open_test_file_btn.setText(_translate("file_reader_dialog", "Open File"))
        self.test_column_header_cb.setText(_translate("file_reader_dialog", "with column header at first row"))
        self.test_row_header_cb.setText(_translate("file_reader_dialog", "with row label at first column"))
        self.groupBox_5.setTitle(_translate("file_reader_dialog", "Or"))
        self.split_method_comb.setItemText(0, _translate("file_reader_dialog", "Random Split"))
        self.split_method_comb.setItemText(1, _translate("file_reader_dialog", "Stratified Shuffle Split"))
        self.label_4.setText(_translate("file_reader_dialog", "by"))
        self.label_3.setText(_translate("file_reader_dialog", "%"))
        self.split_test_fro_train_cb.setText(_translate("file_reader_dialog", "split from the taining file"))
        self.label_5.setText(_translate("file_reader_dialog", "at"))
        self.groupBox_6.setTitle(_translate("file_reader_dialog", "Or"))
        self.without_test_cb.setText(_translate("file_reader_dialog", "without testing file"))
        self.groupBox_2.setTitle(_translate("file_reader_dialog", "Preview"))
        self.apply_btn.setText(_translate("file_reader_dialog", "Apply"))
        self.finish_btn.setText(_translate("file_reader_dialog", "Finish"))
from auxiliary_table import Auxiliary_Table
from open_file_btn import Open_File_Btn
from split_method_combo import Split_Method_Combo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    file_reader_dialog = QtWidgets.QDialog()
    ui = Ui_file_reader_dialog()
    ui.setupUi(file_reader_dialog)
    file_reader_dialog.show()
    sys.exit(app.exec_())
