# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'knn_classifier.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KNN_Dialog(object):
    def setupUi(self, KNN_Dialog):
        KNN_Dialog.setObjectName("KNN_Dialog")
        KNN_Dialog.resize(468, 856)
        self.verticalLayout = QtWidgets.QVBoxLayout(KNN_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_1 = QtWidgets.QGroupBox(KNN_Dialog)
        self.groupBox_1.setObjectName("groupBox_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_1)
        self.groupBox.setEnabled(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.scoring_comb = QtWidgets.QComboBox(self.groupBox)
        self.scoring_comb.setObjectName("scoring_comb")
        self.scoring_comb.addItem("")
        self.scoring_comb.setItemText(0, "")
        self.gridLayout.addWidget(self.scoring_comb, 3, 2, 1, 1)
        self.neighbor_num_sp = QtWidgets.QSpinBox(self.groupBox)
        self.neighbor_num_sp.setMinimum(2)
        self.neighbor_num_sp.setMaximum(100)
        self.neighbor_num_sp.setSingleStep(5)
        self.neighbor_num_sp.setProperty("value", 5)
        self.neighbor_num_sp.setObjectName("neighbor_num_sp")
        self.gridLayout.addWidget(self.neighbor_num_sp, 2, 8, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setStyleSheet("font-size:12px;")
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 2, 6, 1, 2, QtCore.Qt.AlignHCenter)
        self.uniform_cb = QtWidgets.QCheckBox(self.groupBox)
        self.uniform_cb.setChecked(True)
        self.uniform_cb.setObjectName("uniform_cb")
        self.gridLayout.addWidget(self.uniform_cb, 1, 2, 1, 2)
        self.distance_cb = QtWidgets.QCheckBox(self.groupBox)
        self.distance_cb.setChecked(True)
        self.distance_cb.setObjectName("distance_cb")
        self.gridLayout.addWidget(self.distance_cb, 1, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 2)
        self.neighbor_start_sp = QtWidgets.QSpinBox(self.groupBox)
        self.neighbor_start_sp.setToolTip("")
        self.neighbor_start_sp.setStatusTip("")
        self.neighbor_start_sp.setMinimum(2)
        self.neighbor_start_sp.setMaximum(200)
        self.neighbor_start_sp.setSingleStep(10)
        self.neighbor_start_sp.setProperty("value", 3)
        self.neighbor_start_sp.setObjectName("neighbor_start_sp")
        self.gridLayout.addWidget(self.neighbor_start_sp, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setToolTip("")
        self.label.setStatusTip("")
        self.label.setStyleSheet("font-size:12px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setStyleSheet("font-size:12px;")
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 2, 3, 1, 1)
        self.cv_folds_sp = QtWidgets.QSpinBox(self.groupBox)
        self.cv_folds_sp.setMaximum(10)
        self.cv_folds_sp.setProperty("value", 5)
        self.cv_folds_sp.setObjectName("cv_folds_sp")
        self.gridLayout.addWidget(self.cv_folds_sp, 0, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setStyleSheet("font-size:12px;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.neighbor_end_sp = QtWidgets.QSpinBox(self.groupBox)
        self.neighbor_end_sp.setMinimum(5)
        self.neighbor_end_sp.setMaximum(200)
        self.neighbor_end_sp.setSingleStep(10)
        self.neighbor_end_sp.setProperty("value", 10)
        self.neighbor_end_sp.setObjectName("neighbor_end_sp")
        self.gridLayout.addWidget(self.neighbor_end_sp, 2, 4, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_1)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.load_model_cb = QtWidgets.QCheckBox(self.groupBox_4)
        self.load_model_cb.setEnabled(True)
        self.load_model_cb.setObjectName("load_model_cb")
        self.horizontalLayout_2.addWidget(self.load_model_cb)
        self.display_model_name_label = QtWidgets.QLabel(self.groupBox_4)
        self.display_model_name_label.setStyleSheet("")
        self.display_model_name_label.setObjectName("display_model_name_label")
        self.horizontalLayout_2.addWidget(self.display_model_name_label, 0, QtCore.Qt.AlignVCenter)
        self.open_model_btn = Open_Model_Btn(self.groupBox_4)
        self.open_model_btn.setEnabled(False)
        self.open_model_btn.setObjectName("open_model_btn")
        self.horizontalLayout_2.addWidget(self.open_model_btn)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout.addWidget(self.groupBox_1)
        self.groupBox_2 = QtWidgets.QGroupBox(KNN_Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.output_confusion_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.output_confusion_cb.setChecked(True)
        self.output_confusion_cb.setObjectName("output_confusion_cb")
        self.gridLayout_2.addWidget(self.output_confusion_cb, 1, 1, 1, 2)
        self.save_file_btn = Save_File_Btn(self.groupBox_2)
        self.save_file_btn.setEnabled(False)
        self.save_file_btn.setObjectName("save_file_btn")
        self.gridLayout_2.addWidget(self.save_file_btn, 3, 0, 1, 1)
        self.output_cla_rep_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.output_cla_rep_cb.setChecked(True)
        self.output_cla_rep_cb.setObjectName("output_cla_rep_cb")
        self.gridLayout_2.addWidget(self.output_cla_rep_cb, 1, 0, 1, 1)
        self.save_model_label = QtWidgets.QLabel(self.groupBox_2)
        self.save_model_label.setObjectName("save_model_label")
        self.gridLayout_2.addWidget(self.save_model_label, 5, 1, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.plot_roc_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.plot_roc_cb.setChecked(True)
        self.plot_roc_cb.setObjectName("plot_roc_cb")
        self.gridLayout_2.addWidget(self.plot_roc_cb, 0, 0, 1, 1)
        self.save_model_btn = Save_Model_Btn(self.groupBox_2)
        self.save_model_btn.setEnabled(False)
        self.save_model_btn.setObjectName("save_model_btn")
        self.gridLayout_2.addWidget(self.save_model_btn, 5, 0, 1, 1)
        self.save_file_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.save_file_cb.setObjectName("save_file_cb")
        self.gridLayout_2.addWidget(self.save_file_cb, 2, 0, 1, 2)
        self.save_model_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.save_model_cb.setObjectName("save_model_cb")
        self.gridLayout_2.addWidget(self.save_model_cb, 4, 0, 1, 1)
        self.save_file_label = QtWidgets.QLabel(self.groupBox_2)
        self.save_file_label.setObjectName("save_file_label")
        self.gridLayout_2.addWidget(self.save_file_label, 3, 1, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(KNN_Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.widget = QtWidgets.QWidget(KNN_Dialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 20))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apply_btn = QtWidgets.QPushButton(self.widget)
        self.apply_btn.setObjectName("apply_btn")
        self.horizontalLayout.addWidget(self.apply_btn)
        self.reset_btn = QtWidgets.QPushButton(self.widget)
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout.addWidget(self.reset_btn)
        self.finish_btn = QtWidgets.QPushButton(self.widget)
        self.finish_btn.setObjectName("finish_btn")
        self.horizontalLayout.addWidget(self.finish_btn)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(KNN_Dialog)
        QtCore.QMetaObject.connectSlotsByName(KNN_Dialog)

    def retranslateUi(self, KNN_Dialog):
        _translate = QtCore.QCoreApplication.translate
        KNN_Dialog.setWindowTitle(_translate("KNN_Dialog", "KNN_Classifier_Dialog"))
        self.groupBox_1.setTitle(_translate("KNN_Dialog", "parameter setting"))
        self.groupBox.setTitle(_translate("KNN_Dialog", "train a model"))
        self.label_19.setText(_translate("KNN_Dialog", "select"))
        self.uniform_cb.setText(_translate("KNN_Dialog", "uniform"))
        self.distance_cb.setText(_translate("KNN_Dialog", "distance"))
        self.label_6.setToolTip(_translate("KNN_Dialog", "Maximum number of levels in tree"))
        self.label_6.setStatusTip(_translate("KNN_Dialog", "Maximum number of levels in tree"))
        self.label_6.setText(_translate("KNN_Dialog", "Number of Neighbors"))
        self.label_10.setText(_translate("KNN_Dialog", "CV target scoring metrix"))
        self.label.setText(_translate("KNN_Dialog", "Folds for GridSearch Cross Validatin"))
        self.label_20.setText(_translate("KNN_Dialog", "to"))
        self.label_2.setToolTip(_translate("KNN_Dialog", "Number of trees in random forest"))
        self.label_2.setStatusTip(_translate("KNN_Dialog", "Number of trees in random forest"))
        self.label_2.setText(_translate("KNN_Dialog", "weight used in predict"))
        self.groupBox_4.setTitle(_translate("KNN_Dialog", "Or load a model"))
        self.load_model_cb.setText(_translate("KNN_Dialog", "Load Model"))
        self.display_model_name_label.setText(_translate("KNN_Dialog", "No File Selcted"))
        self.open_model_btn.setText(_translate("KNN_Dialog", "Load model(joblib file)"))
        self.groupBox_2.setTitle(_translate("KNN_Dialog", "Out Parameters"))
        self.output_confusion_cb.setText(_translate("KNN_Dialog", "Output confusion matrix"))
        self.save_file_btn.setText(_translate("KNN_Dialog", "Save the Files"))
        self.output_cla_rep_cb.setText(_translate("KNN_Dialog", "Output classification report"))
        self.save_model_label.setText(_translate("KNN_Dialog", "No Directory selected"))
        self.plot_roc_cb.setText(_translate("KNN_Dialog", "Plot ROC on training and testing datsets"))
        self.save_model_btn.setText(_translate("KNN_Dialog", "Save the Model"))
        self.save_file_cb.setText(_translate("KNN_Dialog", "Save (transformed) training (and testng) file(s) to"))
        self.save_model_cb.setText(_translate("KNN_Dialog", "Save fitted model into"))
        self.save_file_label.setText(_translate("KNN_Dialog", "No Directory selected"))
        self.groupBox_3.setTitle(_translate("KNN_Dialog", "Output field"))
        self.apply_btn.setText(_translate("KNN_Dialog", "Apply"))
        self.reset_btn.setText(_translate("KNN_Dialog", "Reset From Previous"))
        self.finish_btn.setText(_translate("KNN_Dialog", "Finish"))
from open_model_btn import Open_Model_Btn
from save_file_btn import Save_File_Btn
from save_model_btn import Save_Model_Btn


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KNN_Dialog = QtWidgets.QDialog()
    ui = Ui_KNN_Dialog()
    ui.setupUi(KNN_Dialog)
    KNN_Dialog.show()
    sys.exit(app.exec_())
