# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lasso_logistic_regression.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(463, 850)
        Dialog.setMinimumSize(QtCore.QSize(0, 20))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_1 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_1.setObjectName("groupBox_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_1)
        self.groupBox.setEnabled(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setStyleSheet("font-size:12px;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.cv_folds_sp = QtWidgets.QSpinBox(self.groupBox)
        self.cv_folds_sp.setMaximum(10)
        self.cv_folds_sp.setProperty("value", 5)
        self.cv_folds_sp.setObjectName("cv_folds_sp")
        self.gridLayout.addWidget(self.cv_folds_sp, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setStyleSheet("font-size:12px;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setStyleSheet("font-size:12px;")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 1, 1, 1)
        self.grid_start_sp = QtWidgets.QSpinBox(self.groupBox)
        self.grid_start_sp.setMinimum(-6)
        self.grid_start_sp.setMaximum(-1)
        self.grid_start_sp.setProperty("value", -2)
        self.grid_start_sp.setObjectName("grid_start_sp")
        self.gridLayout.addWidget(self.grid_start_sp, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setStyleSheet("font-size:12px;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 3, 1, 1)
        self.grid_end_sp = QtWidgets.QSpinBox(self.groupBox)
        self.grid_end_sp.setMinimum(1)
        self.grid_end_sp.setMaximum(6)
        self.grid_end_sp.setProperty("value", 2)
        self.grid_end_sp.setObjectName("grid_end_sp")
        self.gridLayout.addWidget(self.grid_end_sp, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setStyleSheet("font-size:12px;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 5, 1, 1)
        self.grid_num_sp = QtWidgets.QSpinBox(self.groupBox)
        self.grid_num_sp.setMinimum(10)
        self.grid_num_sp.setMaximum(100)
        self.grid_num_sp.setSingleStep(5)
        self.grid_num_sp.setProperty("value", 25)
        self.grid_num_sp.setObjectName("grid_num_sp")
        self.gridLayout.addWidget(self.grid_num_sp, 1, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setStyleSheet("font-size:12px;")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 1, 1, 1)
        self.tol_sp = QtWidgets.QSpinBox(self.groupBox)
        self.tol_sp.setMinimum(-10)
        self.tol_sp.setMaximum(-2)
        self.tol_sp.setObjectName("tol_sp")
        self.gridLayout.addWidget(self.tol_sp, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setStyleSheet("font-size:12px;")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 1, 1, 1)
        self.max_iter_sp = QtWidgets.QSpinBox(self.groupBox)
        self.max_iter_sp.setMinimum(2)
        self.max_iter_sp.setMaximum(5)
        self.max_iter_sp.setObjectName("max_iter_sp")
        self.gridLayout.addWidget(self.max_iter_sp, 3, 2, 1, 1)
        self.balanced_class_weight_cb = QtWidgets.QCheckBox(self.groupBox)
        self.balanced_class_weight_cb.setObjectName("balanced_class_weight_cb")
        self.gridLayout.addWidget(self.balanced_class_weight_cb, 4, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 2)
        self.scoring_comb = QtWidgets.QComboBox(self.groupBox)
        self.scoring_comb.setObjectName("scoring_comb")
        self.scoring_comb.addItem("")
        self.scoring_comb.setItemText(0, "")
        self.gridLayout.addWidget(self.scoring_comb, 5, 2, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_1)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.load_model_cb = QtWidgets.QCheckBox(self.groupBox_4)
        self.load_model_cb.setEnabled(True)
        self.load_model_cb.setObjectName("load_model_cb")
        self.horizontalLayout_2.addWidget(self.load_model_cb)
        self.display_model_name_label = QtWidgets.QLabel(self.groupBox_4)
        self.display_model_name_label.setStyleSheet("")
        self.display_model_name_label.setObjectName("display_model_name_label")
        self.horizontalLayout_2.addWidget(self.display_model_name_label, 0, QtCore.Qt.AlignVCenter)
        self.open_model_btn = Open_Model_Btn(self.groupBox_4)
        self.open_model_btn.setEnabled(False)
        self.open_model_btn.setObjectName("open_model_btn")
        self.horizontalLayout_2.addWidget(self.open_model_btn)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.verticalLayout.addWidget(self.groupBox_1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plot_roc_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.plot_roc_cb.setChecked(True)
        self.plot_roc_cb.setObjectName("plot_roc_cb")
        self.gridLayout_2.addWidget(self.plot_roc_cb, 0, 0, 1, 2)
        self.plot_lasso_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.plot_lasso_cb.setChecked(True)
        self.plot_lasso_cb.setObjectName("plot_lasso_cb")
        self.gridLayout_2.addWidget(self.plot_lasso_cb, 1, 0, 1, 2)
        self.output_cla_rep_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.output_cla_rep_cb.setChecked(True)
        self.output_cla_rep_cb.setObjectName("output_cla_rep_cb")
        self.gridLayout_2.addWidget(self.output_cla_rep_cb, 2, 0, 1, 1)
        self.save_file_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.save_file_cb.setObjectName("save_file_cb")
        self.gridLayout_2.addWidget(self.save_file_cb, 3, 0, 1, 2)
        self.save_file_btn = Save_File_Btn(self.groupBox_2)
        self.save_file_btn.setEnabled(False)
        self.save_file_btn.setObjectName("save_file_btn")
        self.gridLayout_2.addWidget(self.save_file_btn, 4, 0, 1, 1)
        self.save_file_label = QtWidgets.QLabel(self.groupBox_2)
        self.save_file_label.setObjectName("save_file_label")
        self.gridLayout_2.addWidget(self.save_file_label, 4, 1, 1, 1)
        self.save_model_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.save_model_cb.setObjectName("save_model_cb")
        self.gridLayout_2.addWidget(self.save_model_cb, 5, 0, 1, 2)
        self.save_model_btn = Save_Model_Btn(self.groupBox_2)
        self.save_model_btn.setEnabled(False)
        self.save_model_btn.setObjectName("save_model_btn")
        self.gridLayout_2.addWidget(self.save_model_btn, 6, 0, 1, 1)
        self.save_model_label = QtWidgets.QLabel(self.groupBox_2)
        self.save_model_label.setObjectName("save_model_label")
        self.gridLayout_2.addWidget(self.save_model_label, 6, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.output_confusion_cb = QtWidgets.QCheckBox(self.groupBox_2)
        self.output_confusion_cb.setChecked(True)
        self.output_confusion_cb.setObjectName("output_confusion_cb")
        self.gridLayout_2.addWidget(self.output_confusion_cb, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setMinimumSize(QtCore.QSize(0, 20))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.apply_btn = QtWidgets.QPushButton(self.widget)
        self.apply_btn.setObjectName("apply_btn")
        self.horizontalLayout.addWidget(self.apply_btn)
        self.reset_btn = QtWidgets.QPushButton(self.widget)
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout.addWidget(self.reset_btn)
        self.finish_btn = QtWidgets.QPushButton(self.widget)
        self.finish_btn.setObjectName("finish_btn")
        self.horizontalLayout.addWidget(self.finish_btn)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(Dialog)
        self.apply_btn.clicked.connect(Dialog.apply_handler)
        self.finish_btn.clicked.connect(Dialog.finish_handler)
        self.open_model_btn.clicked.connect(Dialog.open_model_btn_clicked_handler)
        self.load_model_cb.toggled['bool'].connect(Dialog.load_model_cb_toggled_handler)
        self.save_model_cb.toggled['bool'].connect(Dialog.save_model_cb_toggled_handler)
        self.save_model_btn.clicked.connect(Dialog.save_model_btn_clicked_handler)
        self.save_file_btn.clicked.connect(Dialog.save_file_btn_clicked_handler)
        self.save_file_cb.toggled['bool'].connect(Dialog.save_file_cb_toggled_handler)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Lasso Logistic Regression"))
        self.groupBox_1.setTitle(_translate("Dialog", "parameter setting"))
        self.groupBox.setTitle(_translate("Dialog", "train a model"))
        self.label.setText(_translate("Dialog", "Folds for Cross Validatin"))
        self.label_2.setText(_translate("Dialog", "Grid Space of Cs from "))
        self.label_9.setText(_translate("Dialog", "10 ^"))
        self.label_3.setText(_translate("Dialog", "to 10 ^"))
        self.label_4.setText(_translate("Dialog", "select"))
        self.label_5.setToolTip(_translate("Dialog", "Tolerance for stopping criteria."))
        self.label_5.setText(_translate("Dialog", "Tolerance"))
        self.label_7.setText(_translate("Dialog", "10 ^"))
        self.label_6.setToolTip(_translate("Dialog", "Maximum number of iterations of the optimization algorithm."))
        self.label_6.setText(_translate("Dialog", "Max_iter"))
        self.label_8.setText(_translate("Dialog", "10 ^"))
        self.balanced_class_weight_cb.setText(_translate("Dialog", "balanced class weight"))
        self.label_10.setText(_translate("Dialog", "CV target scoring metrix"))
        self.groupBox_4.setTitle(_translate("Dialog", "Or load a model"))
        self.load_model_cb.setText(_translate("Dialog", "load Model"))
        self.display_model_name_label.setText(_translate("Dialog", "No File Selcted"))
        self.open_model_btn.setText(_translate("Dialog", "Load model(joblib file)"))
        self.groupBox_2.setTitle(_translate("Dialog", "Out Parameters"))
        self.plot_roc_cb.setText(_translate("Dialog", "Plot ROC on training and testing datsets"))
        self.plot_lasso_cb.setText(_translate("Dialog", "Plot lasso regularizaton profile"))
        self.output_cla_rep_cb.setText(_translate("Dialog", "Output classification report"))
        self.save_file_cb.setText(_translate("Dialog", "save transformed training (and testng) file(s) to"))
        self.save_file_btn.setText(_translate("Dialog", "Save the Files"))
        self.save_file_label.setText(_translate("Dialog", "No Directory selected"))
        self.save_model_cb.setText(_translate("Dialog", "save fitted model into"))
        self.save_model_btn.setText(_translate("Dialog", "Save the Model"))
        self.save_model_label.setText(_translate("Dialog", "No Directory selected"))
        self.output_confusion_cb.setText(_translate("Dialog", "Output confusion matrix"))
        self.groupBox_3.setTitle(_translate("Dialog", "output field"))
        self.apply_btn.setText(_translate("Dialog", "Apply"))
        self.reset_btn.setText(_translate("Dialog", "Reset From Previous"))
        self.finish_btn.setText(_translate("Dialog", "Finish"))
from open_model_btn import Open_Model_Btn
from save_file_btn import Save_File_Btn
from save_model_btn import Save_Model_Btn


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
